---
abstract: 'Number is the range expected'
author:
  - 'Makoto Taniwaki <macopy123@gmail.com >'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::Output: 0
  Test::Requires: 0.06
  Test::Tester: 0.108
  Time::Piece: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::Deep::Between
name: Test-Deep-Between
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Exporter::Lite: 0
  Test::Deep: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mackee/p5-Test-Deep-Between.git
version: 0.02
